import type { Metadata } from "next";
import { poppins } from "@/fonts/poppins";
import "./globals.css";
import NavBar from "@/components/layout/navBar/NavBar";
import Footer from "@/components/layout/footer/Footer";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={poppins.variable}>
      <body className={`${poppins.className}  `}>
        <NavBar />
        <div className="  ">{children}</div>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
